```yaml
name: Deploy marp site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy images and themes
        run: |
          mkdir -p build
          cp -R slides/img build/img
          cp -R slides/themes build/themes

      - name: Marp Build
        uses: docker://marpteam/marp-cli:latest
        with:
          args: --theme-set slides/themes -o build/index.html --html -- slides/Slides.md
        env:
          MARP_USER: root:root

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
